export const homeEventsList = [20250905,20250617,20250519,20250515,20250403,20250308,20250221,20250113,20250105,20241111,]
const eventsData = [
    {
    id: 20251103,
    title: "Presentation at ACM SIGSPATIAL",
    place: "November 3rd - November 6th, 2025, Minneapolis, Minnesota",
    participants: "Minwoo Jeong (M.S. candidate)",
    keywords: "#SIGSPATIAL #LLM #Agent #SUMO",
    desc:
`M.S. candidate Minwoo presented the work “Speak to Simulate: An LLM-Guided Agentic Framework for Traffic Simulation in SUMO,” conducted with M.S. candidate Jeeyun, at the ACM SIGSPATIAL International Workshop on GeoSpatial Simulation (GeoSIM'25)`,
    photos: ['/eventsImg/IMG_6734.jpg', '/eventsImg/IMG_6793.jpg'],
  },
  {
    id: 20250930,
    title: "COEX Exhibition: Smart Life Week 2025",
    place: "September 30th - October 2nd, 2025, Convention and Exhibition Center (COEX)",
    participants: "Professor Yoonjin Yoon, Namwoo Kim (Postdoc Researcher), YoungJoun Park, Juneyoung Ro (M.S. candidate), Keonhee Jang (Integrated M.S.-Ph.D candidate), Seokwoo Yun",
    keywords: "#K-DS",
    desc:
`Our laboratory collaborated with the *MIT Senseable City Lab* at **Smart Life Week 2025**, presenting two exhibitions — “Urban Heat, Urban Sales” and “Feeling Nature” — centered on urban climate, citizens’ daily lives, and climate resilience.

Based on credit card transaction data from 426 administrative districts in Seoul, covering 96 business sectors over 365 days, we quantitatively analyzed how climate factors such as temperature and humidity affect small business owners’ sales and sustainability. Using artificial intelligence, we modeled sales patterns by region and industry under climate stress conditions such as heatwaves and heavy rainfall, and visualized the results as an “Urban Resilience” index.`,
    photos: ['/eventsImg/IMG_0227.jpg', '/eventsImg/IMG_0299.jpg', '/eventsImg/IMG_0306.jpg'],
  },
  {
    id: 20250905,
    title: "K-DS Conference",
    place: "September 5th, 2025, Daegu",
    participants: "Minwoo Jeong (M.S. candidate)",
    keywords: "#K-DS",
    desc:
`M.S. candidate Minwoo presented his work at K-DS conference and won the Best Paper Award.`,
    photos: ['/eventsImg/IMG_5532.jpg', '/eventsImg/IMG_5540.jpg'],
  },
  {
    id: 20250617,
    title: "CAUS Workshop",
    place: "July 17th, 2025, KAIST",
    participants: "Professors, leaders, students participating in CAUS",
    keywords: "#CAUS",
    desc:
`CAUS workshop was held to present the first-year achievements of CAUS and to share the research progress of each lab.`,
    photos: ['/eventsImg/caus250617.jpg'],
  },
  {
    id: 20250616,
    title: "CAUS Monthly Meeting",
    place: "June 16, 2025, KAIST",
    participants: "Professor Yoonjin Yoon, Professor Uichin Lee, students",
    keywords: "#CAUS #Monthly Seminar",
    photos: ['/eventsImg/unnamed(0).jpg', '/eventsImg/unnamed(1).jpg'],
  },
  {
    id: 20250519,
    title: "INFORMS TSL Workshop",
    place: "May 19th-21st, 2025, GLAD Hotel (Yeouido)",
    participants: "Namwoo Kim (Postdoc Researcher), Sungmin Sohn (Ph.D. candidate), Minwoo Jeong (M.S. candidate)",
    keywords: "#INFORMS #TSL",
    photos: ['/eventsImg/unnamed(2).jpg', '/eventsImg/unnamed(3).jpg'],
  },
  {
    id: 20250513,
    title: "CAUS Monthly Meeting",
    place: "May 13, 2025, KAIST",
    participants: "Professor Yoonjin Yoon, Professor Ilchul Moon, Professor Taesik Lee, Professor Minjoon Seo, Professor Changhyun Kwon, Professor Dongman Lee, students",
    keywords: "#CAUS #Monthly Seminar",
    photos: ['/eventsImg/unnamed(4).jpg', '/eventsImg/unnamed(5).jpg'],
  },
  {
    id: 20250318,
    title: "Professor Amy Kim's Visit for CEE seminar",
    place: "March 18, 2025, KAIST",
    participants: "Professor Yoonjin Yoon, Professor Amy Kim, CEE students",
    keywords: "#CEE Seminar",
    desc: 
`*Amy M. Kim* is a Professor of Civil Engineering at the University of British Columbia in Vancouver, 
on the traditional territories of the Musqueam people. 
With the members of her lab, **UBC Multimodal Mobility Systems**, she investigates how long-distance transportation systems perform in connecting people across large geographies, particularly amid disruptions 
caused by natural hazards and other climate change-induced events.

Her work aims to support infrastructure and operational decision-making for climate change adaptation and emergency planning, and to train values-driven, community-minded practitioners and researchers.  

*- BASc in Civil Engineering, University of Waterloo*

*- MS and PhD, University of California, Berkeley*

*- Professional experience in transportation consulting in California and BC*
`,
    photos: ['/eventsImg/unnamed(6).png'],
  },
  {
    id: 20250308,
    title: "Seoul AI Festa",
    place: "March 8~9, 2025, Dongdaemun Design Plaza (DDP)",
    participants: "Professor Yoonjin Yoon, Professor Carlo Ratti (Director of MIT Senseable City Lab), Professor Song Chong (Dean of KAIST Graduate School of AI), Mangi Kim (President of Seoul AI Foundation), Seyun Kim (Research Professor), Minwoo Jeong (M.S. candidate), Juneyoung Ro (M.S. candidate)",
    keywords: "#AI Festa",
    photos: ['/eventsImg/unnamed(7).jpg', '/eventsImg/unnamed(8).jpg', '/eventsImg/unnamed(9).jpg', '/eventsImg/unnamed(10).jpg', '/eventsImg/unnamed(11).jpg'],
  },
  {
    id: 20250113,
    title: "CAUS US Workshop",
    place: "January 13~14, 2025, Stanford University",
    participants: "Professors, leaders, students participating in CAUS",
    keywords: "#CAUS",
    photos: ['/eventsImg/unnamed(12).jpg', '/eventsImg/unnamed(13).jpg', '/eventsImg/unnamed(14).jpg', '/eventsImg/unnamed(15).jpg', '/eventsImg/unnamed(16).jpg'],
  },
  {
    id: 20250105,
    title: "Presentation at TRB Annual Meeting",
    place: "January 5~9, 2025, Washington D.C.",
    participants: "Seyun Kim (Research Professor), Sungmin Sohn (Ph.D. candidate), Donghyun Yoon (Ph.D. candidate), Minwoo Jeong (M.S. candidate)",
    keywords: "#TRB",
    photos: ['/eventsImg/unnamed(17).jpg', '/eventsImg/unnamed(18).jpg', '/eventsImg/unnamed(19).jpg', '/eventsImg/unnamed(20).jpg', '/eventsImg/unnamed(21).jpg'],
  },
  {
    id: 20241212,
    title: "CAUS Regular Meeting - Prof. Changhyun Kwon",
    place: "December 12, 2024, 12:00 pm KST",
    participants: "Prof. Changhyun Kwon, Prof. Yoonjin Yoon, students",
    keywords: "#CAUS",
    photos: ['/eventsImg/unnamed(22).jpg'],
  },
  {
    id: 20241127,
    title: "CAUS Regular Meeting - Prof. Minjoon Seo",
    place: "November 27, 2024, 11:00 am KST",
    participants: "Prof. Minjoon Seo, Prof. Yoonjin Yoon, students",
    keywords: "#CAUS",
  },
  {
    id: 20241126,
    title: "CAUS Regular Meeting - Prof. Taesik Lee",
    place: "November 26, 2024, 17:00 pm KST",
    participants: "Prof. Taesik Lee, Prof. Yoonjin Yoon, students",
    keywords: "#CAUS",
  },
  {
    id: 20241115,
    title: "CAUS 전체미팅",
    place: "November 15, 2024, 10:30 am KST",
    participants: "Prof. Yoonjin Yoon, Prof. Dongman Lee, Prof. Jinkyoo Park, Prof. Changhyun Kwon, Prof. Taesik Lee, Dr. Seonghoon Kim (CTO at Motov), students",
    keywords: "#CAUS",
    photos: ['/eventsImg/unnamed(23).png', '/eventsImg/unnamed(24).png', '/eventsImg/unnamed(25).jpg'],
  },
  {
    id: 20241111,
    title: "K-DS Hackathon: 2nd Prize!",
    place: "November 11-13, 2024, Seoul National University Samsung Convention Center",
    participants: "Donghyun Yoon (Ph.D. candidate), Sungmin Sohn (Ph.D. candidate), Juneyoung Ro (M.S. candidate), Seungro Lee (M.S. candidate)",
    keywords: "#K-DS #Hackathon",
    photos: ['/eventsImg/unnamed(26).jpg', '/eventsImg/unnamed(27).jpg', '/eventsImg/unnamed(28).jpg'],
  },
  {
    id: 20241108,
    title: "한국경영과학회 추계학술대회",
    place: "November 8, 2024, 16:00 pm KST, Korea Aerospace University",
    participants: "Prof. Yoonjin Yoon, Seyun Kim (Research Professor), Namwoo Kim (PostDoc Researcher), Sungmin Sohn (Ph.D. candidate), Donghyun Yoon (Ph.D. candidate)",
    keywords: "#한국경영과학회",
    photos: ['/eventsImg/unnamed(29).jpg', '/eventsImg/unnamed(30).jpg', '/eventsImg/unnamed(31).jpg', '/eventsImg/unnamed(32).jpg', '/eventsImg/unnamed(33).jpg'],
  },
  {
    id: 20241104,
    title: "CAUS Regular Meeting - Prof. Jinkyoo Park",
    place: "November 4, 2024, 14:00 pm KST",
    participants: "Prof. Changhyun Kwon, Prof. Seyun Kim, students",
    keywords: "#CAUS",
    photos: ['/eventsImg/unnamed(34).jpg'],
  },
  {
    id: 20241029,
    title: "CAUS Regular Meeting - Prof. Yoonjin Yoon",
    place: "October 29, 2024, 18:00 pm KST",
    participants: "Prof. Yoonjin Yoon, Prof. Changhyun Kwon, students",
    keywords: "#CAUS",
    photos: ['/eventsImg/unnamed(35).jpg'],
  },
  {
    id: 20241016,
    title: "ICTC Workshop on ETRI Human Understanding AI Paper Challenge (IWETRIAI)",
    place: "October 16, 2024, 13:00 pm KST, Ramada Plaza Hotel, Jeju Island",
    participants: "Juneyoung Ro (M.S. Candidate)",
    keywords: "#ICTC",
    photos: ['/eventsImg/unnamed(36).jpg', '/eventsImg/unnamed(37).jpg', '/eventsImg/unnamed(38).jpg', '/eventsImg/unnamed(39).jpg'],
  },
  {
    id: 20241002,
    title: "CAUS Regular Meeting - Prof. Dongman Lee",
    place: "October 2, 2024, 14:00 pm KST",
    participants: "Prof. Dongman Lee, students",
    keywords: "#CAUS",
  },
  {
    id: 20240925,
    title: "CAUS Kick-Off Meeting (KAIST and GS E&C)",
    place: "September 25, 2024, 15:00 pm KST",
    participants: "Prof. Yoonjin Yoon, Prof. Changhyun Kwon, Prof. Seyun Kim, Prof. Dongman Lee, Prof. Minjoon Seo",
    keywords: "#CAUS",
    photos: ['/eventsImg/unnamed(40).jpg'],
  },
  {
    id: 20240911,
    title: "CAUS Regular Meeting - Prof. Taesik Lee",
    place: "September 11, 2024, 14:00 pm KST",
    participants: "Prof. Yoonjin Yoon, Prof. Taesik Lee, students",
    keywords: "#CAUS",
    photos: ['/eventsImg/unnamed(41).jpg'],
  },
  {
    id: 20240906,
    title: "고속도로 비전 캠퍼스 논문 공모전 장려상 시상식",
    place: "September 6, 2024, 10:00 am KST, 한국도로공사 (Korea Expressway Corporation)",
    participants: "Donghyun Yoon (Ph.D. candidate), Minwoo Jeong (M.S. candidate)",
    keywords: "#한국도로공사",
    photos: ['/eventsImg/unnamed(42).jpg', '/eventsImg/unnamed(43).jpg'],
  },
  {
    id: 20240904,
    title: "CAUS Internal Kick-Off Meeting",
    place: "September 4, 2024, 13:00 pm KST",
    participants: "Prof. Yoonjin Yoon, Prof. Changhyun Kwon, Prof. Taesik Lee, Prof. Dongman Lee, Prof. Jinkyoo Park, Prof. Minjoon Seo",
    keywords: "#CAUS",
    photos: ['/eventsImg/unnamed(44).jpg', '/eventsImg/unnamed(45).jpg'],
  },
  {
    id: 20240822,
    title: "CAUS MoU Signing Ceremony",
    place: "August 22, 2024, 14:30 pm KST",
    keywords: "#CAUS",
    photos: ['/eventsImg/unnamed(46).jpg', '/eventsImg/unnamed(47).jpg', '/eventsImg/unnamed(48).jpg'],
  },
  {
    id: 20240731,
    title: "CAUS Regular Meeting - Prof. Changhyun Kwon",
    place: "July 31, 2024, 13:00 pm KST (zoom)",
    participants: "Prof. Changhyun Kwon, students",
    keywords: "#CAUS",
  },
  {
    id: 20240723,
    title: "CAUS Regular Meeting - Prof. Dongman Lee",
    place: "July 23, 2024, 10:00 am KST",
    participants: "Prof. Dongman Lee, students",
    keywords: "#CAUS",
  },
  {
    id: 20240719,
    title: "CAUS Regular Meeting - Prof. Minjoon Seo",
    place: "July 19, 2024, 14:00 pm KST (zoom)",
    participants: "Prof. Minjoon Seo, students",
    keywords: "#CAUS",
  },
  {
    id: 20240710,
    title: "CAUS Regular Meeting - Prof. Taesik Lee",
    place: "July 10, 2024, 13:00 pm KST",
    participants: "Prof. Taesik Lee, students",
    keywords: "#CAUS",
  },
  {
    id: 20240621,
    title: "CAUS Meeting",
    place: "June 21, 2024, 09:00 am KST",
    participants: "Prof. Yoonjin Yoon, Prof. Changhyun Kwon, GS, students",
    keywords: "#CAUS",
    photos: ['/eventsImg/unnamed(49).jpg'],
  },
  {
    id: 20240422,
    title: "Study group meeting with professors",
    place: "April 22, 2024, 19:00 pm KST",
    participants: "Prof. Jinkyoo Park, Prof. Minjoon Seo, Speaker: Yuyol Shin (Ph.D, Postdoctoral Researcher, KAIST)",
    keywords: "#traffic forecasting",
    photos: ['/eventsImg/unnamed(50).jpg'],
  },
  {
    id: 20240321,
    title: "Professor Kincho Law's Visit",
    place: "March 21, 2024, 16:00 pm KST",
    participants: "Speaker: Prof. Kincho Law, Professor of Civil and Environmental Engineering, Stanford University",
    keywords: "#civil infrastructures",
    desc: 
`**Talk:** Cyber Physical System for Civil Infrastructures`,
    photos: ['/eventsImg/unnamed(51).jpg', '/eventsImg/unnamed(52).jpg', '/eventsImg/unnamed(53).jpg', '/eventsImg/unnamed(54).jpg'],
  },
  {
    id: 20231208,
    title: "Urban@KAIST Urban-X Seminar",
    place: "Dec. 8, 2023, 10:00 am KST",
    participants: "Speaker: Prof. Dongman Lee, Provost and Executive Vice President, KAIST; Professor, School of Computing, KAIST",
    keywords: "#Human flows #Urban space",
    desc: "Understanding Urban State Changes via Human Flow Analysis",
    photos: ['/eventsImg/unnamed(55).png'],
  },
  {
    id: 20231201,
    title: "Urban@KAIST Urban-X Seminar",
    place: "Dec. 1, 2023, 10:00 am KST",
    participants: "Speaker: Prof. Daniel Vignon, Assistant Professor, Civil and Urban Engineering, NYU",
    keywords: "#mobility #policy #economics",
    desc: "Safety, Liability, and Insurance Markets in the Age of Automated Driving",
    youtube:"https://www.youtube-nocookie.com/embed/D18TnNnS3J0?si=UrcX5zxZD-tLeENU"
  },
  {
    id: 20231124,
    title: "Urban@KAIST Urban-X Seminar",
    place: "Nov. 24, 2023, 10:00 am KST",
    participants: "Speaker: Prof. Lisa Lim, Assistant Professor, Civil and Environmental Engineering, KAIST",
    keywords: "#design #health",
    desc: "Improving Health through Design of Cities and Buildings",
    youtube:"https://www.youtube-nocookie.com/embed/kHNgVpuIa7A?si=NUBGw3hZEnLuhkyY"
  },
  {
    id: 20231117,
    title: "Urban@KAIST Urban-X Seminar",
    place: "Nov. 17, 2023, 10:00 am KST",
    participants: "Speaker: Dr. Boyeong Hong, Associate Research Scholar, NYU Marron Institute of Urban Management; Adjunct Professor, Columbia University",
    keywords: "#mobility #climatechange #health #policy #inequality",
    desc: "Responsible and Responsive City - The Next Phase of Urban Planning",
    photos: ['/eventsImg/unnamed(56).png'],
  },
  {
    id: 20231110,
    title: "Urban@KAIST Urban-X Seminar",
    place: "Nov. 10, 2023, 10:00 am KST",
    participants: "Speaker: Prof. Jihee Kim, Associate Professor, School of Business and Technology Management, KAIST",
    keywords: "#economic development",
    desc: "A Human-machine Collaborative Approach Measures Economic Development Using Satellite Imagery",
    youtube:"https://www.youtube-nocookie.com/embed/CZH92bvJwcc?si=S_MLoFMdZHeAwd1A"
  },
  // [... continue adding remaining events in same format ...]
];
export default eventsData;
